@startuml

' avoid problems with angled crows feet
skinparam linetype ortho

package 定性ドメイン {
    entity "企業"
    entity "企業詳細"
    entity "産業種別"
    entity "役員"
    entity "役員種別"
    entity "沿革"
    entity "沿革種別"
    entity "地域"
}

package 業績ドメイン {
    entity "通期業績"
    entity "年別業績"
    entity "業績種別"
}

package 認証ドメイン {
    entity "管理者"
}

' リレーションの定義
企業 ||--o| 企業詳細
企業 ||--o{ 年別業績
企業 ||--o{ 通期業績
企業 ||--o{ 沿革
企業 ||--o{ 役員
沿革 }o--|| 役員
沿革 }|--|| 沿革種別
沿革 }o--|| 地域
役員種別 ||--o{ 役員
企業詳細 }o--|| 産業種別
業績種別 ||--o{ 年別業績

@enduml
